### YamlMime:ManagedReference
items:
- uid: System.Windows.Data.ValueUnavailableException
  id: ValueUnavailableException
  children:
  - System.Windows.Data.ValueUnavailableException.#ctor
  - System.Windows.Data.ValueUnavailableException.#ctor(System.String)
  - System.Windows.Data.ValueUnavailableException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Windows.Data.ValueUnavailableException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ValueUnavailableException
  nameWithType: ValueUnavailableException
  fullName: System.Windows.Data.ValueUnavailableException
  type: Class
  summary: "Által okozott kivételek a &lt;xref:System.Windows.Data.BindingGroup.GetValue%28System.Object%2CSystem.String%29?displayProperty=fullName&gt; metódust, ha az érték nem érhető el."
  syntax:
    content: 'public class ValueUnavailableException : SystemException'
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Data.ValueUnavailableException.#ctor
  id: '#ctor'
  parent: System.Windows.Data.ValueUnavailableException
  langs:
  - csharp
  name: ValueUnavailableException()
  nameWithType: ValueUnavailableException.ValueUnavailableException()
  fullName: System.Windows.Data.ValueUnavailableException.ValueUnavailableException()
  type: Constructor
  assemblies:
  - PresentationFramework
  namespace: System.Windows.Data
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Windows.Data.ValueUnavailableException&quot;> </xref> osztály."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonság az új példány egy rendszer által megadott üzenetet, amely leírja a hibát, például a &quot;Rendszerhiba történt.&quot;</xref:System.Exception.Message%2A> Ez az üzenet figyelembe veszi a rendszer jelenlegi kulturális környezethez.       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Windows.Data.ValueUnavailableException>.</xref:System.Windows.Data.ValueUnavailableException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| Az üzenet honosított hibakarakterlánc. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ValueUnavailableException ();
    parameters: []
  overload: System.Windows.Data.ValueUnavailableException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Data.ValueUnavailableException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Windows.Data.ValueUnavailableException
  langs:
  - csharp
  name: ValueUnavailableException(String)
  nameWithType: ValueUnavailableException.ValueUnavailableException(String)
  fullName: System.Windows.Data.ValueUnavailableException.ValueUnavailableException(String)
  type: Constructor
  assemblies:
  - PresentationFramework
  namespace: System.Windows.Data
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Windows.Data.ValueUnavailableException&quot;> </xref> a megadott üzenet osztályra."
  remarks: "A tartalmát a `message` paraméter érthető, a felhasználónak kell lennie. Ez a konstruktor védőfalkezelőbe szükség, győződjön meg arról, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított.       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Windows.Data.ValueUnavailableException>.</xref:System.Windows.Data.ValueUnavailableException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ValueUnavailableException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Az üzenet, amely leírja a hibát."
  overload: System.Windows.Data.ValueUnavailableException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Data.ValueUnavailableException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Windows.Data.ValueUnavailableException
  langs:
  - csharp
  name: ValueUnavailableException(SerializationInfo,StreamingContext)
  nameWithType: ValueUnavailableException.ValueUnavailableException(SerializationInfo,StreamingContext)
  fullName: System.Windows.Data.ValueUnavailableException.ValueUnavailableException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - PresentationFramework
  namespace: System.Windows.Data
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Windows.Data.ValueUnavailableException&quot;> </xref> a szerializált adatok osztályt."
  syntax:
    content: protected ValueUnavailableException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Windows.Data.ValueUnavailableException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Data.ValueUnavailableException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Windows.Data.ValueUnavailableException
  langs:
  - csharp
  name: ValueUnavailableException(String,Exception)
  nameWithType: ValueUnavailableException.ValueUnavailableException(String,Exception)
  fullName: System.Windows.Data.ValueUnavailableException.ValueUnavailableException(String,Exception)
  type: Constructor
  assemblies:
  - PresentationFramework
  namespace: System.Windows.Data
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Windows.Data.ValueUnavailableException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmazhat egy hivatkozást az előző kivétel a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság, amely a konstruktorban, vagy egy null hivatkozás át ugyanazon értékét adja vissza (`Nothing` a Visual Basic nyelvben) Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.SystemException>.</xref:System.SystemException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A belső kivétel referencia. |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ValueUnavailableException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem egy null hivatkozás (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> a Visual Basic nyelvben), a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.Windows.Data.ValueUnavailableException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Windows.Data.ValueUnavailableException.#ctor
  parent: System.Windows.Data.ValueUnavailableException
  isExternal: false
  name: ValueUnavailableException()
  nameWithType: ValueUnavailableException.ValueUnavailableException()
  fullName: System.Windows.Data.ValueUnavailableException.ValueUnavailableException()
- uid: System.Windows.Data.ValueUnavailableException.#ctor(System.String)
  parent: System.Windows.Data.ValueUnavailableException
  isExternal: false
  name: ValueUnavailableException(String)
  nameWithType: ValueUnavailableException.ValueUnavailableException(String)
  fullName: System.Windows.Data.ValueUnavailableException.ValueUnavailableException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Data.ValueUnavailableException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Windows.Data.ValueUnavailableException
  isExternal: false
  name: ValueUnavailableException(SerializationInfo,StreamingContext)
  nameWithType: ValueUnavailableException.ValueUnavailableException(SerializationInfo,StreamingContext)
  fullName: System.Windows.Data.ValueUnavailableException.ValueUnavailableException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Windows.Data.ValueUnavailableException.#ctor(System.String,System.Exception)
  parent: System.Windows.Data.ValueUnavailableException
  isExternal: false
  name: ValueUnavailableException(String,Exception)
  nameWithType: ValueUnavailableException.ValueUnavailableException(String,Exception)
  fullName: System.Windows.Data.ValueUnavailableException.ValueUnavailableException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Windows.Data.ValueUnavailableException.#ctor*
  parent: System.Windows.Data.ValueUnavailableException
  isExternal: false
  name: ValueUnavailableException
  nameWithType: ValueUnavailableException.ValueUnavailableException
