### YamlMime:ManagedReference
items:
- uid: System.Workflow.Activities.Rules.RuleEvaluationException
  id: RuleEvaluationException
  children:
  - System.Workflow.Activities.Rules.RuleEvaluationException.#ctor
  - System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String)
  - System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RuleEvaluationException
  nameWithType: RuleEvaluationException
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException
  type: Class
  summary: "Az összes szabály értékelése problémák okozta kivétel alaposztálya jelöli."
  syntax:
    content: 'public class RuleEvaluationException : System.Workflow.Activities.Rules.RuleException'
  inheritance:
  - System.Exception
  - System.Workflow.Activities.Rules.RuleException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor
  id: '#ctor'
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  langs:
  - csharp
  name: RuleEvaluationException()
  nameWithType: RuleEvaluationException.RuleEvaluationException()
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException()
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Workflow.Activities.Rules.RuleEvaluationException&quot;> </xref> osztály."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonság az új példány egy rendszer által megadott üzenetet, amely leírja a hibát, és figyelembe veszi a rendszer aktuális kulturális környezetének.</xref:System.Exception.Message%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Workflow.Activities.Rules.RuleEvaluationException>.</xref:System.Workflow.Activities.Rules.RuleEvaluationException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| A rendszer által megadott honosított leírás. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleEvaluationException ();
    parameters: []
  overload: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  langs:
  - csharp
  name: RuleEvaluationException(String)
  nameWithType: RuleEvaluationException.RuleEvaluationException(String)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(String)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Workflow.Activities.Rules.RuleEvaluationException&quot;> </xref> osztály egy adott hiba miatt."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonságának az új példány használatával a `message` paraméter.</xref:System.Exception.Message%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Workflow.Activities.Rules.RuleEvaluationException>.</xref:System.Workflow.Activities.Rules.RuleEvaluationException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleEvaluationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Az üzenet, amely leírja a hibát."
  overload: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  langs:
  - csharp
  name: RuleEvaluationException(SerializationInfo,StreamingContext)
  nameWithType: RuleEvaluationException.RuleEvaluationException(SerializationInfo,StreamingContext)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Workflow.Activities.Rules.RuleEvaluationException&quot;> </xref> a szerializált adatokban osztályt."
  remarks: "Ez a konstruktor nevezzük az adatfolyam továbbított kivétel objektum meglévő kölcsönökre deszerializálás közben."
  syntax:
    content: protected RuleEvaluationException (System.Runtime.Serialization.SerializationInfo serializeInfo, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: serializeInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> , amely tartalmazza a kivétel lépett fel az éppen szerializált objektum adatait."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>, amely a cél- és környezeti információkat tartalmaz.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  langs:
  - csharp
  name: RuleEvaluationException(String,Exception)
  nameWithType: RuleEvaluationException.RuleEvaluationException(String,Exception)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(String,Exception)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Workflow.Activities.Rules.RuleEvaluationException&quot;> </xref> osztály egy megadott hibaüzenet és a belső <xref:System.Exception>, amely okozza-e <xref:System.Exception>.</xref:System.Exception> </xref:System.Exception> mutató hivatkozás"
  remarks: "Egy <xref:System.Exception>, amely egy előző közvetlen emiatt történt <xref:System.Exception>hivatkozni kell a korábbi kivétel a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> </xref:System.Exception> </xref:System.Exception> A <xref:System.Exception.InnerException%2A>tulajdonság, amely a konstruktorban, vagy egy null hivatkozás át ugyanazon értékét adja vissza (`Nothing`) Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső <xref:System.Exception>érték a konstruktor.</xref:System.Exception> </xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Workflow.Activities.Rules.RuleEvaluationException>.</xref:System.Workflow.Activities.Rules.RuleEvaluationException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A belső <xref:System.Exception>referencia. |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleEvaluationException (string message, Exception ex);
    parameters:
    - id: message
      type: System.String
      description: "Az üzenet, amely leírja a hibát."
    - id: ex
      type: System.Exception
      description: "<xref:System.Exception>Amely az aktuális <xref:System.Exception>.</xref:System.Exception> oka</xref:System.Exception> Ha a `innerException` paraméter nem egy null hivatkozás (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> a Visual Basic nyelvben), az aktuális <xref:System.Exception>egy catch blokkba, amely kezeli a belső <xref:System.Exception>.</xref:System.Exception> jelenik meg</xref:System.Exception>"
  overload: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: System.Workflow.Activities.Rules.RuleException
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException()
  nameWithType: RuleEvaluationException.RuleEvaluationException()
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException()
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String)
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException(String)
  nameWithType: RuleEvaluationException.RuleEvaluationException(String)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException(SerializationInfo,StreamingContext)
  nameWithType: RuleEvaluationException.RuleEvaluationException(SerializationInfo,StreamingContext)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String,System.Exception)
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException(String,Exception)
  nameWithType: RuleEvaluationException.RuleEvaluationException(String,Exception)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException
  nameWithType: RuleEvaluationException.RuleEvaluationException
