### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.AddressAlreadyInUseException
  id: AddressAlreadyInUseException
  children:
  - System.ServiceModel.AddressAlreadyInUseException.#ctor
  - System.ServiceModel.AddressAlreadyInUseException.#ctor(System.String)
  - System.ServiceModel.AddressAlreadyInUseException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.ServiceModel.AddressAlreadyInUseException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: AddressAlreadyInUseException
  nameWithType: AddressAlreadyInUseException
  fullName: System.ServiceModel.AddressAlreadyInUseException
  type: Class
  summary: "A kivétel fordul elő, amikor egy cím nem érhető el, mert már használatban van."
  remarks: "Ez a kivétel származik <xref:System.ServiceModel.CommunicationException>helyreállítható hibák, lehetséges, hogy jelezni, végpontok közötti kommunikáció során robusztus osztály jelöli, amelyek [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] ügyfél és a szolgáltatásalkalmazásokhoz is kezelni kellene.</xref:System.ServiceModel.CommunicationException> A kezelő- <xref:System.ServiceModel.CommunicationException>a pontosabb AddressAlreadyInUseException elfogja a rendszer a findlogin a <xref:System.ServiceModel.CommunicationException>.</xref:System.ServiceModel.CommunicationException> kezelése előtt</xref:System.ServiceModel.CommunicationException> megelőzése"
  syntax:
    content: 'public class AddressAlreadyInUseException : System.ServiceModel.CommunicationException'
  inheritance:
  - System.ServiceModel.CommunicationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor
  id: '#ctor'
  parent: System.ServiceModel.AddressAlreadyInUseException
  langs:
  - csharp
  name: AddressAlreadyInUseException()
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException()
  fullName: System.ServiceModel.AddressAlreadyInUseException.AddressAlreadyInUseException()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.AddressAlreadyInUseException&quot;> </xref> osztály."
  syntax:
    content: public AddressAlreadyInUseException ();
    parameters: []
  overload: System.ServiceModel.AddressAlreadyInUseException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.AddressAlreadyInUseException
  langs:
  - csharp
  name: AddressAlreadyInUseException(String)
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException(String)
  fullName: System.ServiceModel.AddressAlreadyInUseException.AddressAlreadyInUseException(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.AddressAlreadyInUseException&quot;> </xref> osztály egy adott hiba miatt."
  remarks: "Ez a konstruktor használható, ha a felhasználó hibaüzenetet átadni. Az üzenet paraméter lehet az arra jogosult felhasználók értelmezhetők."
  syntax:
    content: public AddressAlreadyInUseException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
  overload: System.ServiceModel.AddressAlreadyInUseException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.ServiceModel.AddressAlreadyInUseException
  langs:
  - csharp
  name: AddressAlreadyInUseException(SerializationInfo,StreamingContext)
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException(SerializationInfo,StreamingContext)
  fullName: System.ServiceModel.AddressAlreadyInUseException.AddressAlreadyInUseException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.AddressAlreadyInUseException&quot;> </xref> a szerializálási adat szerepel, és a megadott adatfolyam-kontextus osztályt."
  remarks: "Ez a konstruktor nevezik helyreállítására az adatfolyam továbbított kivétel objektum deszerializálása közben."
  syntax:
    content: protected AddressAlreadyInUseException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> tartalmazó szerializálni a kivételt szükséges összes adatot."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>, amely megadja, hogy a forrás- és az adatfolyam.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.ServiceModel.AddressAlreadyInUseException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.ServiceModel.AddressAlreadyInUseException
  langs:
  - csharp
  name: AddressAlreadyInUseException(String,Exception)
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException(String,Exception)
  fullName: System.ServiceModel.AddressAlreadyInUseException.AddressAlreadyInUseException(String,Exception)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.AddressAlreadyInUseException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e a kivételt, a osztályt."
  remarks: "Ez a konstruktor használható, ha egy hibaüzenet és a belső kivételt, akár a felhasználó információt. Az üzenet paraméter lehet a kívánt értelmezhetők.       Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmazhat egy hivatkozást az előző kivétel a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza vagy egy `null` hivatkozás (`Nothing` a Visual Basic nyelvben) Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public AddressAlreadyInUseException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
    - id: innerException
      type: System.Exception
      description: "A <xref:System.Exception>, hogy jelezni, hogy az adott kivételt okozott.</xref:System.Exception>"
  overload: System.ServiceModel.AddressAlreadyInUseException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.CommunicationException
  isExternal: false
  name: System.ServiceModel.CommunicationException
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor
  parent: System.ServiceModel.AddressAlreadyInUseException
  isExternal: false
  name: AddressAlreadyInUseException()
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException()
  fullName: System.ServiceModel.AddressAlreadyInUseException.AddressAlreadyInUseException()
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor(System.String)
  parent: System.ServiceModel.AddressAlreadyInUseException
  isExternal: false
  name: AddressAlreadyInUseException(String)
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException(String)
  fullName: System.ServiceModel.AddressAlreadyInUseException.AddressAlreadyInUseException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.ServiceModel.AddressAlreadyInUseException
  isExternal: false
  name: AddressAlreadyInUseException(SerializationInfo,StreamingContext)
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException(SerializationInfo,StreamingContext)
  fullName: System.ServiceModel.AddressAlreadyInUseException.AddressAlreadyInUseException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor(System.String,System.Exception)
  parent: System.ServiceModel.AddressAlreadyInUseException
  isExternal: false
  name: AddressAlreadyInUseException(String,Exception)
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException(String,Exception)
  fullName: System.ServiceModel.AddressAlreadyInUseException.AddressAlreadyInUseException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.ServiceModel.AddressAlreadyInUseException.#ctor*
  parent: System.ServiceModel.AddressAlreadyInUseException
  isExternal: false
  name: AddressAlreadyInUseException
  nameWithType: AddressAlreadyInUseException.AddressAlreadyInUseException
